# SAM configuration file
version = 0.1

[default.deploy]
[default.deploy.parameters]
stack_name = "luis-swe-project"
s3_bucket = ""  # SAM will create this
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = []
image_repositories = []
resolve_s3 = true
s3_prefix = "luis-swe-project"


[default.global.parameters]
region = "us-east-2"
